services:
  redis:
    image: redis
  mongo:
    image: mongo
  worker:
    image: proteus/worker
    build:
      context: .
      dockerfile: bin/worker/Dockerfile
    volumes:
      - scope_data:/app/scope
    depends_on:
    - redis
    - mongo
  api:
    image: proteus/api
    build:
      context: bin/api/
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
    - '127.0.0.1:80:80'
    volumes:
      - scope_data:/app/scope
    depends_on:
      - redis

volumes:
  scope_data:
